/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Datos.Datos;
import Modelo.Proveedores;
import com.mycompany.mitienda.MiTienda;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        nuevaVenta = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        agregarACatalogo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelCatalogosProv = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoProveedorTxtArea = new javax.swing.JTextArea();
        editarProveedorButton = new javax.swing.JButton();
        eliminarProveedorButton = new javax.swing.JButton();
        labelBuscar = new javax.swing.JLabel();
        fieldBuscar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Compra-Ventas");

        jPanel2.setForeground(java.awt.SystemColor.activeCaption);

        jTabbedPane1.setBackground(java.awt.SystemColor.textHighlight);
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jDesktopPane4.setBackground(java.awt.SystemColor.activeCaption);

        nuevaVenta.setText("Nueva Venta");
        nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentaActionPerformed(evt);
            }
        });

        jDesktopPane4.setLayer(nuevaVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(nuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(898, Short.MAX_VALUE))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(nuevaVenta)
                .addContainerGap(693, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jDesktopPane4);

        jDesktopPane3.setBackground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", jDesktopPane3);

        jDesktopPane2.setBackground(java.awt.SystemColor.activeCaption);
        jDesktopPane2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        productosTabla.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        productosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(productosTabla);

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Catalogo general");

        agregarACatalogo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        agregarACatalogo.setText("Agregar Productos al Catalogo");
        agregarACatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarACatalogoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Buscar Productos");

        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(agregarACatalogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(agregarACatalogo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarACatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Productos", jDesktopPane2);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Compras", jDesktopPane5);

        jDesktopPane6.setBackground(java.awt.SystemColor.activeCaption);

        tablaProveedores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedores.setColumnSelectionAllowed(true);
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
        });
        tablaProveedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaProveedoresKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProveedores);
        tablaProveedores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelCatalogosProv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCatalogosProv.setForeground(new java.awt.Color(0, 0, 0));
        labelCatalogosProv.setText("Catalogo de Proveedores");

        infoProveedorTxtArea.setColumns(20);
        infoProveedorTxtArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        infoProveedorTxtArea.setRows(5);
        jScrollPane3.setViewportView(infoProveedorTxtArea);

        editarProveedorButton.setForeground(new java.awt.Color(0, 0, 0));
        editarProveedorButton.setText("Editar");
        editarProveedorButton.setEnabled(false);
        editarProveedorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProveedorButtonActionPerformed(evt);
            }
        });

        eliminarProveedorButton.setBackground(new java.awt.Color(255, 102, 102));
        eliminarProveedorButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarProveedorButton.setText("Eliminar");
        eliminarProveedorButton.setEnabled(false);
        eliminarProveedorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProveedorButtonActionPerformed(evt);
            }
        });

        labelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        labelBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(0, 0, 0));
        labelBuscar.setText("Buscar:");

        fieldBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fieldBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fieldBuscarCaretUpdate(evt);
            }
        });

        jDesktopPane6.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(labelCatalogosProv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(editarProveedorButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(eliminarProveedorButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(labelBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(fieldBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane6Layout.createSequentialGroup()
                        .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                                .addComponent(labelCatalogosProv, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(editarProveedorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eliminarProveedorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(108, 108, 108))))
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCatalogosProv)
                            .addComponent(labelBuscar)
                            .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(editarProveedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarProveedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Proveedores", jDesktopPane6);

        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenu1.setText("File");

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaVentaActionPerformed

    private void agregarACatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarACatalogoActionPerformed
        // TODO add your handling code here:
        nuevoCatalogo nc= new nuevoCatalogo();
        nc.setVisible(true);
        nc.setResizable(false);
        nc.setEnabled(true);
        nc.setLocationRelativeTo(null);
    }//GEN-LAST:event_agregarACatalogoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       nuevoProveedor nv = new nuevoProveedor(false);
       nv.setVisible(true);
       nv.setResizable(false);
       nv.setEnabled(true);
       nv.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaProveedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProveedoresKeyPressed
          mostrarEnAreaInfo();
    }//GEN-LAST:event_tablaProveedoresKeyPressed

    private void mostrarEnAreaInfo(){
        this.editarProveedorButton.setEnabled(true);
        this.eliminarProveedorButton.setEnabled(true);
        int filaSeleccionada = tablaProveedores.getSelectedRow();
        String id1 = (String)tablaProveedores.getValueAt(filaSeleccionada, 0);
        int id = Integer.parseInt(id1);
        for (int i = 0; i < MiTienda.datosProveedores.size(); i++) {
            if(MiTienda.datosProveedores.get(i).getId()==id){
                Proveedores p=MiTienda.datosProveedores.get(i);
                infoProveedorTxtArea.setText("Id: "+p.getId()+"\nNombre: "+p.getNombre()+"\nTelefono: "+p.getTelefono()+"\nDireccion: "+p.getDireccion() +"\nCiudad: "+
                    p.getCiudad() + "\nEmail: "+p.getEmail() + "\n\nApuntes importantes: \n\""+p.getApuntes()+"\"");
                i=MiTienda.datosProveedores.size()+1;
            }

        }
    }
    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked

        mostrarEnAreaInfo();
        // Lo imprimimos en pantalla
        //System.out.println(id);
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void editarProveedorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProveedorButtonActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaProveedores.getSelectedRow();
        String id1 = (String)tablaProveedores.getValueAt(filaSeleccionada, 0);
        int id = Integer.parseInt(id1);
        for (int i = 0; i < MiTienda.datosProveedores.size(); i++) {
            if(MiTienda.datosProveedores.get(i).getId()==id){
                Proveedores p=MiTienda.datosProveedores.get(i);
                nuevoProveedor np = new nuevoProveedor(true);
                np.setVisible(true);
                np.setLocationRelativeTo(null);
                np.llenarCamposParaModificar(p);
                np.setResizable(false);
                np.setEnabled(true);
                i=MiTienda.datosProveedores.size()+1;
            }
        }
    }//GEN-LAST:event_editarProveedorButtonActionPerformed

    private void eliminarProveedorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProveedorButtonActionPerformed
        // TODO add your handling code here:
        String numeroUno="";
        for (int i = 0; i < 5; i++) {
            Random rn = new Random();
            int answer = rn.nextInt(10) + 1;
            numeroUno+=answer;
        }
        int filaSeleccionada = tablaProveedores.getSelectedRow();
        String id1 = (String)tablaProveedores.getValueAt(filaSeleccionada, 0);
        int id = Integer.parseInt(id1);
        String number="";
        Proveedores p= new  Proveedores();
        for (int i = 0; i < MiTienda.datosProveedores.size(); i++) {
            if(MiTienda.datosProveedores.get(i).getId()==id){
                p=MiTienda.datosProveedores.get(i);
                number = JOptionPane.showInputDialog("Tome en cuenta que se eliminaran todos los registros con este nombre!"
                        + "\nPara eliminar el proveedor: "+p.getNombre()+"\n Ingrese el codigo: \n\t\t"+numeroUno);
                i=MiTienda.datosProveedores.size()+1;
            }
        }
       
        if(number.equals(numeroUno)){
            //eliminar
            MiTienda.datosProveedores.remove(filaSeleccionada);
            MiTienda.llenarTablaProveedores(MiTienda.datosProveedores);
            Datos dt= new Datos();
            dt.eliminarProveedor(p.getId(), MiTienda.conexion);
            this.editarProveedorButton.setEnabled(false);
            this.eliminarProveedorButton.setEnabled(false);
            this.infoProveedorTxtArea.setText("");
            JOptionPane.showMessageDialog(this, "Se ha eliminado el proveedor");
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese el codigo correcto");
        }
        
    }//GEN-LAST:event_eliminarProveedorButtonActionPerformed

    private void fieldBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fieldBuscarCaretUpdate
        // TODO add your handling code here:
        if(fieldBuscar.getText().equalsIgnoreCase(" ")){
            MiTienda.llenarTablaProveedores(MiTienda.datosProveedores);
        }else{
            ArrayList<Proveedores> listaP = new ArrayList<>();
            for (int i = 0; i < MiTienda.datosProveedores.size(); i++) {
                boolean contiene= MiTienda.datosProveedores.get(i).getNombre().contains(fieldBuscar.getText());
                if(contiene){
                    listaP.add(MiTienda.datosProveedores.get(i));
                }
            }
            MiTienda.llenarTablaProveedores(listaP);
        }
        //this.labelBuscar.setText(this.fieldBuscar.getText());
        
    }//GEN-LAST:event_fieldBuscarCaretUpdate
/**/
    /**
    * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarACatalogo;
    private javax.swing.JButton editarProveedorButton;
    private javax.swing.JButton eliminarProveedorButton;
    private javax.swing.JTextField fieldBuscar;
    public static javax.swing.JTextArea infoProveedorTxtArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCatalogosProv;
    private javax.swing.JButton nuevaVenta;
    public javax.swing.JTable productosTabla;
    public javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
}
